import * as TypeR from 'type-r';
import Backbone from './backbone';
import { RestCollection, RestModel } from './rest';
import { LazyStore, RestStore } from './rest-store';
export * from 'type-r';
export * from './backbone';
export { Backbone, RestStore, LazyStore, RestCollection as Collection, RestModel as Model };
export declare const Class: typeof TypeR.Messenger;
declare const Nested: typeof TypeR & typeof Backbone;
export default Nested;
export declare function defaults(x: any): typeof Nested.Record;
